### ISSUE TITLE
Please fix repo layout 

### ISSUE THREAD

**Issue by watkinspd** [bcgov/SIndexR#1]
Hi, we need your repo to conform to the guidelines. Check:
https://github.com/bcgov/BC-Policy-Framework-For-GitHub/blob/master/BC-Gov-Org-HowTo/Cheatsheet.md

And
https://github.com/bcgov/BC-Policy-Framework-For-GitHub

A nice example to follow is here:
https://github.com/bcgov/bcgroundwater

Contact angelika.ehlers@gov.bc.ca if you have questions.

Thanks.

**Comment by YongLuo007** [comment]
Thanks Peter,
I added the must-have files in the repo. Could you please have a look and let me know whether they meet the standard? 
Thanks again.
Yong

**Comment by agehlers** [comment]
Thanks for taking care of this. We appreciate it. Angelika

**Comment by agehlers** [comment]
Repo conforms to BCGov guideline.
